#!/bin/bash
temp=$(sensors coretemp-isa-0000 | grep -i "Package id 0:" | cut -d"+" -f2 | cut -d" " -f1)
dec=${temp::-4}
if [[ $dec -ge 80 ]];
then
	echo "$temp"
	echo ""
	echo "#FF0000"
elif [[ $dec -ge 70 && $dec -lt 80 ]];
then
	echo "$temp"
	echo ""
	echo "#FFA500"
elif [[ $dec -ge 60 && $dec -lt 70 ]];
then
	echo "$temp"
	echo ""
	echo "#FFDA29"
elif [[ $dec -ge 50 && $dec -le 60 ]];
then
	echo "$temp"
	echo ""
	echo "#ADFF2F"
elif [[ $dec -le 50 ]];
then
	echo "$temp"
	echo ""
	echo "#00FF00"
fi
